# Generated by Django 3.1.4 on 2020-12-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0002_auto_20201201_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='post_images/'),
        ),
    ]
