# Generated by Django 3.1.3 on 2020-11-22 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewPost',
            new_name='Event',
        ),
    ]
