# Generated by Django 3.1.3 on 2020-12-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20201122_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='post_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
