# Generated by Django 3.1.3 on 2020-12-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_event_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='thumbnumber',
            field=models.IntegerField(default=0),
        ),
    ]
