# Generated by Django 3.1.4 on 2020-12-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20201207_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='post_images/'),
        ),
    ]
